#!/usr/bin/env python
import os,sys,httplib2,re,random;  _ = len(sys.argv)>1 and sys.argv[1] and os.system('clear'); print random.choice(re.findall(r"(\<\!\[CDATA\[.*\]\])",httplib2.Http().request("http://bash.im/rss")[1])).decode("cp1251").encode("utf8").split("<![CDATA[")[1].split("]]")[0].replace("&quot;", "\"").replace("<br>", "\n").replace("&gt;",">").replace("&lt;","<")
